# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: track_trips
  pool: 5
  username: root
  password: password

development_sec:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: track_trips_archive
  pool: 5
  username: root
  password: password

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: track_trips_test
  pool: 5
  username: root
  password: password


